=== FelixNeufeld/DistributedSystemsWI22-23/Chat/src/de/hrw/dsalab/distsys/chat/XML/config.dtd
<!ELEMENT chatTool (font, communication, shortcuts, theme)>

<!ELEMENT font (fontName, size)>
<!ELEMENT fontName (#PCDATA)>
<!ELEMENT size (#PCDATA)>

<!ELEMENT communication (connection, port)>
<!ELEMENT connection (#PCDATA)>
<!ELEMENT port (#PCDATA)>

<!ELEMENT shortcuts (shortcut+)>
<!ELEMENT shortcut EMPTY>
<!ATTLIST shortcut
        action CDATA #REQUIRED
        key CDATA #REQUIRED>

<!ELEMENT theme (#PCDATA)>

=== FelixNeufeld/DistributedSystemsWI22-23/Chat/src/de/hrw/dsalab/distsys/chat/XML/config.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE chatTool SYSTEM "file:///C:/Users/Neufe/Desktop/Felix/Projects/Uni/Distributed Systems/DistributedSystemsWI22-23/Chat/src/de/hrw/dsalab/distsys/chat/XML/config.dtd">
<chatTool>
    <font>
        <fontName>Calibri</fontName>
        <size>20</size>
    </font>

    <communication>
        <connection>Socket</connection>
        <port>1337</port>
    </communication>

    <shortcuts>
        <shortcut action="send_message" key="Enter"/>
    </shortcuts>

    <theme>Dark</theme>
</chatTool>
